### ISSUE TITLE
大江戸Ruby会議07 ページラフ

### ISSUE THREAD

**Issue by llminatoll** [asakusarb/oedo07#1]
湊川あいです。やんちゃさんよりお声がけいただきました。よろしくお願いします！

**Comment by llminatoll** [comment]
ざっくりラフを描きました

- 雷5656会館というテーマに合わせて、風神雷神
- 雷ということで、黄色メインのサブカラー黒

アイデアありましたらぜひよろしくお願いします😊
![2ba64a24-e4bc-42cc-9a4e-6b359b364f56](https://user-images.githubusercontent.com/22927920/41597613-dfe948a0-7408-11e8-9a86-f78a98a0a411.png)

**Comment by llminatoll** [comment]
［Memo］埋め込みGoogle mapを雷神カラーにカスタマイズしたい
https://snazzymaps.com

**Comment by llminatoll** [comment]
[メモ]アタマの部分だけでも早く作る

# ざっくり情報整理

- タイトル
    - 『大江戸 Ruby 会議 07』 Asakusa.rb 
- とき
    - 2018 年 9 月 15 日（土）
- ばしょ
    - 浅草にある『雷5656会館』の 5, 6 階『ときわホール』（めっちゃイカす会場です）
- 内容
    - Matzさんがテクい話をする？
    - Jonanさん登壇？

**Comment by llminatoll** [comment]
[Memo]風神雷神図屏風の著作権について、念のため調べました ⚡️ ⛈ 

> ポスターへの風神雷神のキャラ転用は特に断ることなく行って構いません。
> 理由は、著作権が切れているからです。
> なお、写真の著作権を侵すことになるのではないかという心配もまずありません。

参考：　https://detail.chiebukuro.yahoo.co.jp/qa/question_detail/q1214442792

**Comment by llminatoll** [comment]
@amatsuda 

>  固有名詞

なるほど！そこまで気が回らずすみません。ご対応いただきありがとうございます😊🙏✨

> 京都 / ゴロゴロっぽい

確かに、言われてみれば京都のですよね・・！笑
私自身、関西出身ですが違和感ありませんでした、なんというか日本全体としての国宝というイメージがありました🎉
（ツッコミくるかしら・・・もし来たら、風神雷神関係なく、ただ単に「カミナリ雲に乗った鬼」のイラストにしてもいいかもですね）

**Comment by amatsuda** [comment]
いやいやー、風神雷神カッコイイからいいんじゃないでしょうかー！

**Comment by llminatoll** [comment]
では風神雷神で行きましょう！

**Comment by june29** [comment]
通りすがりにコメントします！

https://mantan-web.jp/article/20180624dog00m200002000c.html

> 2枚ということだったので、まず風神雷神の画（え）が浮かびました。“両巨頭”の画を描くにあたり、初代（ジョナサン・ジョースター）でもよかったのですが、以前に富士山をバックに、何枚か承太郎を描いたことがあったんです。また（ディオのバックに描いた）月や（承太郎のバックの）富士山という普遍的なもの、背景もほしかったんです。

なんと荒木飛呂彦さんもジョジョの原画展で「風神雷神」のメタファーの話をしていました。奇妙な友情すら感じちゃいますね…！

**Comment by llminatoll** [comment]
なんと！ジョジョ好きなので興味深いです👀✨

**Comment by kakutani** [comment]
https://regional.rubykaigi.org/oedo07/ で見えるようになっちゃいました

↓が見えちゃってるけどトップイメージがかっこいいからまあいっか、と 🙈 
<img width="1026" alt="integrity" src="https://user-images.githubusercontent.com/2160/42089186-26dd6932-7bd7-11e8-99fb-b40104b4d80b.png">

**Comment by llminatoll** [comment]
@kakutani 
すみません、サンプルメッセージ見えてましたね

すぐ調整します〜！

**Comment by llminatoll** [comment]
@kakutani 
対応しました〜
https://regional.rubykaigi.org/oedo07/

**Comment by kakutani** [comment]
かくにんしました〜。ときにこのissue、どうなったら閉じますかね(もう閉じてもいいんじゃまいか派 🇯🇲

**Comment by llminatoll** [comment]
閉じました〜 😄 ありがとうございますmm
