### ISSUE TITLE
かわいい系イラストの場合

### ISSUE THREAD

**Issue by llminatoll** [asakusarb/oedo07#9]
かわいい系で描いてみたテスト
![default](https://user-images.githubusercontent.com/22927920/42097715-c79d0672-7bf3-11e8-86cb-c232ed637f9a.jpg)

**Comment by llminatoll** [comment]
### 所感
- 万人にとって好き嫌いが分かれない絵柄にしてみました
- ホンモノに近いイラストよりも、デフォルメした方がオリジナリティー感出てていいかも？

みなさんの意見も聞いてみたいです〜

**Comment by hsbt** [comment]
めちゃかわだ... 僕はこういうクリエイティブは好きです!

**Comment by amatsuda** [comment]
なるほどなるほど。今までにないテイストでとても良いですね！
どっちみち今のもののままってことはないと思うので、サクッと適用しちゃって良いと思います！

細かい疑問としては、風神くんの表情が、＞＜ なのかニッコリなのか、記号的によくわからないなー、と思いました。たぶんニッコリしてるんでしょうけど。

**Comment by llminatoll** [comment]
ありがとうございます！
はい、ニッコリの意味の><ですね！

ちょっと直してみました。
![raijin_d](https://user-images.githubusercontent.com/22927920/42132526-8de81fae-7d54-11e8-97b1-c6b23a35a8c0.png)

それでは一旦これで適用しますね！
